version: '3.8'

services:
  rabbitmq:
    extends:
      file: org.mutagen.evraz.rabbitmq/docker-compose.yml
      service: rabbitmq
    env_file: ".env"
  mongo:
    extends:
      file: org.mutagen.evraz.mongodb/docker-compose.yml
      service: mongo
    env_file: ".env"


networks:
  mutagen-backend:
    name: mutagen-evraz-backend
